apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-model
  labels:
    app: titanic-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: titanic-model
  template:
    metadata:
      labels:
        app: titanic-model
    spec:
      containers:
      - name: model
        image: <REGISTRY>/titanic-model:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_URI
          value: "models:/titanic-rf/Production" # or provide S3 path or local
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
